contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
baseurl       = "https://matiasvj.gitlab.io/"
title         = "Matias Verdier | Software Developer"
canonifyurls  = true
theme         = "hyde"

[indexes]
  category  = "categories"
